services:
  dev-linkki-web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: dev-linkki-web
    volumes:
      - .:/project
    ports:
      - "8080:8080"

volumes:
  project: