baseURL = 'https://linkkijkl.fi'
title = 'Linkki Jyväskylä ry.'
theme = ["hugo-embed-pdf-shortcode"]
enableInlineShortcodes = true

# Number of posts per page
pagination.pagerSize = 10

# Don't pluralize title pages by default
pluralizeListTitles = false

staticDir = ["static"]

defaultContentLanguage = 'fi'
[languages]

    [languages.fi]
        disabled = false
        languageCode = 'fi'
        languageName = 'Suomi'
        weight = 1

    [languages.en]
        disabled = false
        languageCode = 'en'
        languageName = 'English'
        weight = 2

[outputs]
home = ["html", "rss", "api-sponsors"]

[mediaTypes."application/json"]
    suffixes = [ "json" ]

[outputFormats]
    [outputFormats.API-Sponsors]
        mediaType = "application/json"
        baseName = "api/sponsors"
        isPlainText = true

[languages.fi.menus]

[[languages.fi.menus.main]]
    name = "Yhdistys"
    identifier = "menu.yhdistys"
    weight = 1

[[languages.fi.menus.main]]
    name = "Säännöt ja ohjeet"
    identifier = "menu.saannot"
    url = "/säännöt/"
    parent = "menu.yhdistys"
    weight = 1

[[languages.fi.menus.main]]
    name = "Hallitus"
    identifier = "menu.hallitus"
    url = "/hallitus/"
    parent = "menu.yhdistys"
    weight = 2


[[languages.fi.menus.main]]
    name = "Järjestön historia"
    identifier = "menu.historia"
    url = "/historia/"
    parent = "menu.yhdistys"
    weight = 3


[[languages.fi.menus.main]]
    name = "Jäsenyys"
    identifier = "menu.jäsenyys"
    url = "/jäsenyys/"
    parent = "menu.yhdistys"
    weight = 4


[[languages.fi.menus.main]]
    name = "Jäsenedut"
    identifier = "menu.jäsenedut"
    url = "/jäsenedut/"
    parent = "menu.yhdistys"
    weight = 5


[[languages.fi.menus.main]]
    name = "Kunniamaininnat"
    identifier = "menu.kunniamaininnat"
    url = "/kunniamaininnat/"
    parent = "menu.yhdistys"
    weight = 6


[[languages.fi.menus.main]]
    name = "Pöytäkirjat"
    identifier = "menu.pöytäkirjat"
    url = "/pöytäkirjat/"
    parent = "menu.yhdistys"
    weight = 7


[[languages.fi.menus.main]]
    name = "Toiminta"
    identifier = "menu.toiminta"
    weight = 2


[[languages.fi.menus.main]]
    name = "Tapahtumat"
    identifier = "menu.tapahtumat"
    url = "/tapahtumat/"
    parent = "menu.toiminta"
    weight = 1

#[[languages.fi.menus.main]]
#    name = "Vappu 2025"
#    identifier = "menu.vappu"
#    url = "/blog/vappu2025"
#    parent = "menu.toiminta"
#    weight = 1

[[languages.fi.menus.main]]
    name = "Kattila"
    identifier = "menu.kattila"
    url = "/kattila/"
    parent = "menu.toiminta"
    weight = 2


[[languages.fi.menus.main]]
    name = "Tenttiarkisto"
    identifier = "menu.tenttiarkisto"
    url = "/tenttiarkisto/"
    parent = "menu.toiminta"
    weight = 3


[[languages.fi.menus.main]]
    name = "Laitteistovuokraus"
    identifier = "menu.vuokraus"
    url = "/laitteistovuokraus/"
    parent = "menu.toiminta"
    weight = 4


[[languages.fi.menus.main]]
    name = "Haalarimerkit"
    identifier = "menu.haalarimerkit"
    url = "/haalarimerkit/"
    parent = "menu.toiminta"
    weight = 5


[[languages.fi.menus.main]]
    name = "Keskustelukanavat"
    identifier = "menu.keskustelukanavat"
    url = "/keskustelukanavat/"
    parent = "menu.toiminta"
    weight = 6


[[languages.fi.menus.main]]
    name = "Lukupiiri"
    identifier = "menu.lukupiiri"
    url = "/lukupiiri/"
    parent = "menu.toiminta"
    weight = 7


[[languages.fi.menus.main]]
    name = "Uudelle opiskelijalle"
    identifier = "menu.fuksit"
    url = "/fuksit/"
    parent = "menu.toiminta"
    weight = 8


[[languages.fi.menus.main]]
    name = "Yhteistyö"
    identifier = "menu.yhteistyö"
    url = "/yhteistyö/"
    weight = 4


[[languages.fi.menus.main]]
    name = "Blogi"
    identifier = "menu.blog"
    url = "/blog/"
    weight = 5


[[languages.fi.menus.main]]
    name = "A href"
    identifier = "menu.ahref"
    url = "/a-href/"
    weight = 6



[languages.en.menus]

[[languages.en.menus.main]]
    name = "Association"
    identifier = "menu.yhdistys"
    weight = 1


[[languages.en.menus.main]]
    name = "Rules and guides"
    identifier = "menu.saannot"
    url = "/en/rules/"
    parent = "menu.yhdistys"
    weight = 1


[[languages.en.menus.main]]
    name = "Board"
    identifier = "menu.hallitus"
    url = "/en/board/"
    parent = "menu.yhdistys"
    weight = 2


#[[languages.en.menus.main]]
#    name = "History"
#    identifier = "menu.historia"
#    url = "/en/yhdistys/historia/"
#    parent = "menu.yhdistys"
#    weight = 3


[[languages.en.menus.main]]
    name = "Membership"
    identifier = "menu.jäsenyys"
    url = "/en/membership/"
    parent = "menu.yhdistys"
    weight = 4


[[languages.en.menus.main]]
    name = "Membership Benefits"
    identifier = "menu.jäsenedut"
    url = "/en/benefits/"
    parent = "menu.yhdistys"
    weight = 5


[[languages.en.menus.main]]
    name = "Honorary mentions"
    identifier = "menu.kunniamaininnat"
    url = "/en/honorary-mentions/"
    parent = "menu.yhdistys"
    weight = 6


[[languages.en.menus.main]]
    name = "Board Minutes"
    identifier = "menu.pöytäkirjat"
    url = "/en/minutes/"
    parent = "menu.yhdistys"
    weight = 7


[[languages.en.menus.main]]
    name = "Activity"
    identifier = "menu.toiminta"
    weight = 2


[[languages.en.menus.main]]
    name = "Events"
    identifier = "menu.tapahtumat"
    url = "/en/events/"
    parent = "menu.toiminta"
    weight = 1

#[[languages.en.menus.main]]
#    name = "Vappu 2025"
#    identifier = "menu.vappu"
#    url = "/en/blog/vappu2025"
#    parent = "menu.toiminta"
#    weight = 1

[[languages.en.menus.main]]
    name = "Kattila"
    identifier = "menu.kattila"
    url = "/en/kattila/"
    parent = "menu.toiminta"
    weight = 2


[[languages.en.menus.main]]
    name = "Exam Archive"
    identifier = "menu.tenttiarkisto"
    url = "/en/exam-archive/"
    parent = "menu.toiminta"
    weight = 3


[[languages.en.menus.main]]
    name = "Equipment Rental"
    identifier = "menu.vuokraus"
    url = "/en/equipment-rental/"
    parent = "menu.toiminta"
    weight = 4


[[languages.en.menus.main]]
    name = "Overall Patches"
    identifier = "menu.haalarimerkit"
    url = "/en/overall-patches/"
    parent = "menu.toiminta"
    weight = 5


[[languages.en.menus.main]]
    name = "Chat"
    identifier = "menu.keskustelukanavat"
    url = "/en/chat/"
    parent = "menu.toiminta"
    weight = 6


[[languages.en.menus.main]]
    name = "Book club"
    identifier = "menu.lukupiiri"
    url = "/book-club/"
    parent = "menu.toiminta"
    weight = 7


[[languages.en.menus.main]]
    name = "New Students"
    identifier = "menu.fuksit"
    url = "/en/fuksit/"
    parent = "menu.toiminta"
    weight = 8


[[languages.en.menus.main]]
    name = "Collaboration"
    identifier = "menu.yhteistyö"
    url = "/en/collaboration/"
    weight = 4


[[languages.en.menus.main]]
    name = "Blog"
    identifier = "menu.blog"
    url = "/en/blog/"
    weight = 5


[[languages.en.menus.main]]
    name = "A href"
    identifier = "menu.ahref"
    url = "/en/a-href/"
    weight = 6



[params]
    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    mainSections = ["blog", "a-href", "hallitus"]

    defaultKeywords = ["linkkijkl", "linkki", "jyväskylä"]

    address = """
            <p class="text-uppercase"><strong>Linkki Jyväskylä ry (2147178-4)</strong><br/>
            Opiskelijatila Kattila (Agora, Ag B102)<br/>
            PL 35, 40014 Jyväskylän yliopisto<br/><br/>
            <a href="mailto:hallitus@linkkijkl.fi">hallitus@linkkijkl.fi</a></p><br/>
            <a href="https://t.me/linkkijkl_info"><i class='fab fa-2x fa-telegram'></i></a>
            <a href="https://discord.com/invite/f9c6y97"><i class='fab fa-2x fa-discord'></i></a>
            <a href="https://instagram.com/linkkijkl"><i class='fab fa-2x fa-instagram'></i></a>
            <a href="https://github.com/linkkijkl"><i class='fab fa-2x fa-github'></i></a>
            <a href="https://www.facebook.com/linkkijkl"><i class='fab fa-2x fa-facebook'></i></a>
            <a href="https://www.youtube.com/@LinkkiJyvaskylaRy"><i class='fab fa-2x fa-youtube'></i></a>
    """
    contact_url = ""

    logo_text = "img/logo/linkki-navbar.svg"
    logo_text_condenced = "img/logo/linkki-navbar-condenced.svg"
    logo = "img/logo/linkki-logo-simple.svg"

    # Format dates with Go's time formatting
    # https://pkg.go.dev/time
    date_format = "2.1.2006"

    dropdown_mouse_over = false

    modified_by_url = "https://github.com/linkkijkl/linkki-web/graphs/contributors"

    # Prefetch theese domains from DNS
    prefetch_domains = ["kattila.linkkijkl.fi"]


[languages.fi.params]
    about_us = """
            <a class="text-uppercase" href="/säännöt/#jäsenrekisteriseloste">
                <strong>Tietosuojaseloste</strong>
            </a>
            <br/>
            <a class="text-uppercase" href="/säännöt/">
                <strong>Säännöt</strong>
            </a>
    """
    invoicing = """
            <p class="text-uppercase">
                Suosimme verkkolaskutusta!<br/>
                <br/>
                Verkkolaskuosoite: <strong>003721471784</strong><br/>
                Operaattoritunnus: <strong>OKOYFIHH</strong><br/>
                Välittäjä: <strong>OP Osuuskunta</strong><br/>
                Sähköposti: <strong>raha@linkkijkl.fi</strong><br/>
            </p>
    """


[languages.en.params]
    about_us = """
            <a class="text-uppercase" href="/en/rules">
                <strong>Privacy policy</strong>
            </a>
            <br/>
            <a class="text-uppercase" href="/en/rules">
                <strong>Rules</strong>
            </a>
    """
    invoicing = """
            <p class="text-uppercase">
                We prefer e-invoicing!<br/>
                <br/>
                E-billing address: <strong>003721471784</strong><br/>
                Operator ID: <strong>OKOYFIHH</strong><br/>
                Operator: <strong>OP Osuuskunta</strong><br/>
                Email: <strong>raha@linkkijkl.fi</strong><br/>
            </p>
    """

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.


[languages.fi.params.clients]
    title = "Yhteistyössä"


[languages.en.params.clients]
    title = "Our sponsors"


[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    link_url = "https://forms.gle/ZRYsBxLazFVM111Q8"


[languages.fi.params.see_more]
    link_text = "Avaa liittymislomake"
    title = "Liity jäseneksi"
    subtitle = "Ainejärjestön jäsenyys tarkoittaa perinteisesti elämänmittaisia kaverisuhteita ja juuri opiskelijan näköistä opiskelijakulttuuria."


[languages.en.params.see_more]
    link_text = "Application form"
    title = "Membership application"
    subtitle = "Joining a student union traditionally equates to lifelong friendships and memorable experiences in student culture."


[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"


[params.recent_posts]
    enable = true
    hide_summary = true


[languages.fi.params.recent_posts]
    title = "Uusimmat päivitykset"


[languages.en.params.recent_posts]
    title = "Recent updates"


[markup.tableOfContents]
    endLevel = 1
    startLevel = 1


# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = true

[params.footer.recent_posts]
    enable = false